# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.


plugins: [jekyll-paginate]
# Setup
title:               Sahit PJ's website
tagline:             'A little mix of Tech, Coolness and Nerdiness'
description:         
url:                 
baseurl:             ''
paginate:            5
future: true

# About/contact
author:
  name:              Jayakrishna Sahit
  url:               https://twitter.com/sahitpj  
  email:             jayakrishna.sahit@iitgn.ac.in

# Custom vars
version:             1.0.0
